# Generated by Django 5.0 on 2023-12-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootStrapAdmin', '0004_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='payment_type',
            field=models.CharField(choices=[('Credit Card Payment', 'Credit'), ('Debit Card Payment', 'Debit'), ('Cash Payment', 'Cash')], default=('Credit Card Payment', 'Credit'), max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_size',
            field=models.IntegerField(default=0),
        ),
    ]
