# Generated by Django 5.0 on 2023-12-16 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootStrapAdmin', '0005_alter_rent_payment_type_alter_vehicle_engine_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='rent',
            name='customer',
        ),
        migrations.DeleteModel(
            name='RentStatus',
        ),
        migrations.AddField(
            model_name='rent',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BootStrapAdmin.customer'),
        ),
    ]
