# Generated by Django 5.0 on 2023-12-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootStrapAdmin', '0006_alter_rent_status_remove_rent_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='preview',
            field=models.ImageField(null=True, upload_to='images_test'),
        ),
    ]
