# Generated by Django 5.0 on 2023-12-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BootStrapAdmin', '0015_rent_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
