# Generated by Django 5.0 on 2023-12-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BootStrapAdmin', '0022_rename_model_name_model_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='model_type',
        ),
    ]
