# Generated by Django 5.0 on 2023-12-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootStrapAdmin', '0024_alter_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='payment_type',
            field=models.CharField(choices=[('Credit Card Payment', 'Credit_Card'), ('Debit Card Payment', 'Debit_Card'), ('Cash Payment', 'Cash')], default=('Credit Card Payment', 'Credit_Card'), max_length=100),
        ),
    ]
